[package]
name = "IntegerMate"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "testnet-0.28.0" }

[addresses]
integer_mate =  "0x0"
sui =  "0x0000000000000000000000000000000000000002"
